services:
  - type: web
    name: ofrezco-app
    plan: free
    region: oregon 
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT app.main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: "0"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: APP_NAME
        value: Ofrezco
      - key: DATABASE_URL
        value: sqlite:///./data.db
