services:
  - type: web
    name: ofrezco-app
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ofrezco-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: "0"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: APP_NAME
        value: Ofrezco

databases:
  - name: ofrezco-db
    plan: free
